apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flaskdeployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:

      containers:
      - name: flask-container
        image: derradjisenani/backend_webapp:latest
        ports:
        - containerPort: 5000
#        resources:
#           requests:
#             memory: "100Mi"
#             cpu: "10m"
#           limits:
#             memory: "128Mi"
#             cpu: "15m"

        env:
        - name: DB_HOST
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: MYSQL_HOST

        - name: DB_PASSWORD
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: MYSQL_PASSWORD

        - name: DB_NAME
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: MYSQL_DATABASE

        - name: DB_USER
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: MYSQL_USER

        - name: REDIS_HOST
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: REDIS_HOST

        - name: REDIS_PASSWORD
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: REDIS_PASSWORD
               
        - name: REDIS_PORT
          value: "6379"

        - name: SECRET_KEY
          valueFrom :
             secretKeyRef:
               name: flask-secret 
               key: SECRET_KEY
        
